config/routes.rb
Rails.application.routes.draw do
  get '/home',       to: 'static_pages#home'

  resources :users
  resources :rosters
  resources :players
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 2..30 },
                                   uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validate  :password_validation
  has_secure_password

  has_one :roster

  private

  def password_validation
    errors.add(:password, "can't be identical to username") if password == name;
    errors.add(:password, "can't contain spaces") if password =~ /\s+/
    errors.add(:password, "has to contain at least one digit") if password !~ /\d+/
    errors.add(:password, "has to contain at least one uppercase letter") if password !~ /[A-Z]+/
    errors.add(:password, "has to contain at least one lowercase letter") if password !~ /[a-z]+/
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_admin, except: [:new, :create, :show]
  before_action :proper_user, only: [:show]


  def index
    @users = User.all
  end

  def new
    if logged_in?
      flash[:warning] = "Already logged in"
      redirect_to current_user
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Sign up complete!"
      redirect_to @user
    else
      flash[:danger] = "Unable to create user!"
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "User deleted successfully!"
    else
      flash[:warning] = "Unable to delete user!"
    end
    redirect_to users_path
  end

  def show
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    user = User.find_by(id: params[:id])
    if user == current_user || !admin?
      flash[:danger] = "Access denied!"
      redirect_to edit_user_path(user)
    else
      user.update_attribute(:admin, params[:admin])
      flash[:success] = "Successfully updated user!"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def proper_user
    @user = User.find_by(id: params[:id])
    unless @user == current_user
      flash[:danger] = "Access denied!"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h1 Edit user

.center
  %h2= @user.name
  = form_tag @user, method: :patch do
    .form-check
      %label{for: "admin"} Admin 
      = check_box_tag "admin", true, @user.admin
    = button_tag "Save", class: "btn btn-orange"
  = link_to "Back", users_path

app/views/users/index.html.haml
%h1 Users

%table.table
  %thead
    %tr
      %th Id
      %th Username
      %th Admin?
      %th Roster
      %th Actions
  %tbody
    - @users.each_with_index do |user|
      %tr
        %td= user.id
        %td= user.name
        %td= user.admin ? "Yes" : "No"
        %td
          - unless user.roster.nil?
            = link_to "See roster", user.roster
          - else
            N/A
        %td
          = link_to "Edit", edit_user_path(user), class: "btn btn-orange"
          = link_to "Delete", user_path(user), class: "btn btn-orange",  method: :delete,
                                               data: { confirm: "Are you sure?" }

app/views/users/new.html.haml
%h1 Sign up

%div.row
  %div.col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name

      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation

      = f.submit "Sign up", class: "btn btn-orange"

app/views/users/show.html.haml
%h1 My profile

%h2= @user.name

.center
  - unless @user.roster.nil?
    %p
      Prediction correctness:
      = Roster.final_roster.nil? ? "N/A" : number_to_percentage(@user.roster.result, precision: 2)
    = link_to "See your roster", roster_path(@user.roster), class: "btn btn-lg btn-orange"
  - else
    = link_to "Create roster", new_roster_path, class: "btn btn-lg btn-orange"