config/routes.rb
Rails.application.routes.draw do
  get '/home',       to: 'static_pages#home'

  resources :users
  resources :rosters
  resources :players
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: 'static_pages#home'
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true, length: { in: 2..50 },
                                   uniqueness: { case_sensitive: false }
  validates :position, presence: true, length: { minimum: 1 },
                                   inclusion: { in: %w[QB RB FB WR TE OL DL LB CB S K P LS] }

  def self.positions
    %w[QB RB FB WR TE OL DL LB CB S K P LS]
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :logged_in_admin
  
  def new
    @player = Player.new  
  end

  def edit
    @player = Player.find_by(id: params[:id])
  end

  def update
    @player = Player.find_by(id: params[:id])
    @player.attributes = player_params
    if @player.save
      flash[:success] = "Player succesfully updated"
      redirect_to players_path
    else
      flash[:danger] = @player.errors.full_messages.first
      redirect_to edit_player_path(@player)
    end

  end
 
  def create
    @player = Player.new(name: params[:name], position: params[:position], active: params[:active])
    if @player.save
      flash[:success] = "Player succesfully created"
      redirect_to players_path
    else
      flash[:danger] = @player.errors.full_messages.first
      render 'new'
    end
  end

  def index
    @players = Player.all.order(:name)
  end

  def destroy
    @player = Player.find_by(id: params[:id])
    if @player.destroy
      flash[:success] = "Player succesfully deleted"
    else
      flash[:danger] = "Unable to destroy player"
    end
    redirect_to players_path
  end

  private

  def player_params
    params.permit(:name, :position, :active)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_players_form.html.haml
= label :name, "Name"
= text_field_tag :name, @player.name

= label :position, "Position"
= select_tag :position, options_for_select(Player.positions, @player.position)

= label :status, "Status"
= select_tag :active, options_for_select([["Active",true], ["Inactive", false]], @player.active)

= submit_tag "Save", class: "btn btn-orange"
.center
  %p= link_to "Back", players_path, class: "center"

app/views/players/edit.html.haml
%h2 Edit player

.row
  .col-md-6.col-md-offset-3
    = form_tag @player, method: :patch do
      = render 'players/players_form'

app/views/players/index.html.haml
%h2 Players
%table.table.table-condensed.table-bordered.table-responsive
  %thead
    %tr
      %th #
      %th Name
      %th Pos.
      %th.center Status
      %th.center Actions
  %tbody
    - @players.each_with_index do |player, index|
      %tr
        %td= "#{index + 1}."
        %td= player.name
        %td= player.position
        %td.center= player.active ? "Active" : "Inactive"
        %td.center
          = link_to "Edit", edit_player_path(player), class: "btn btn-orange"
          = link_to "Delete", player_path(player), class: "btn btn-orange", method: :delete,
                                                   data: { confirm: "Are you sure?" } 
    %tr
      %td.center{colspan: 5}= link_to "Add player", new_player_path, class: "btn btn-roster btn-orange"

app/views/players/new.html.haml
%h2 Add player

.row
  .col-md-6.col-md-offset-3
    = form_tag players_path do
      = render 'players/players_form'
    